runtime: go114
env: standard
handlers:
- url: /.*
  script: _go_app
env_variables:
  INSTANCE_UNIX_SOCKET: true-kite-361808:us-central1:pg-sample
  DB_USER: admin
  DB_PASS: admin
  DB_NAME: db-sample